name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Hugging Face
        env:
          HF_ACCESS_TOKEN: ${{ secrets.HF_ACCESS_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token $HF_ACCESS_TOKEN
          # Skip repo creation if it already exists
          huggingface-cli repo create Axkars_Space -y || echo "Repository already exists, skipping creation."
          git lfs install
          git init
          git remote set-url origin https://huggingface.co/spaces/Axkar/Axkars_Space
          git add .
          git commit -m "Deploy to Hugging Face Space"
          git push origin main --force
