name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Hugging Face
        env:
          HF_ACCESS_TOKEN: ${{ secrets.HF_ACCESS_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token $HF_ACCESS_TOKEN
          huggingface-cli repo create Axkars_Space -y || echo "Repo already exists."
          git lfs install
          git config user.name "Ax-kar"
          git config user.email "axkzek69@gmail.com"
          if git remote get-url origin; then
            git remote set-url origin https://huggingface.co/spaces/Axkar/Axkars_Space
          else
            git remote add origin https://huggingface.co/spaces/Axkar/Axkars_Space
          fi
          git fetch --unshallow || echo "Repository is already fully fetched."
          git add .
          git commit -m "Deploy to Hugging Face Space" || echo "Nothing to commit."
          git push origin main --force
